### ISSUE TITLE
[Help] How to setting chart container size the right way ?

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [wuba/react-native-echarts#109]
Hi, i want to ask about How to setting chart container size the right way ?

The chart not adapt its container with wrapper view even when i set same size (CHART_SIZE) for both view and chart.

Width = 380
![Screenshot 2023-09-12 at 10 13 44](https://github.com/wuba/react-native-echarts/assets/30792140/f664b569-9707-4d9e-8dee-f438b14a378b)

CHART_SIZE = 320 // want it expected
![Screenshot 2023-09-12 at 10 14 48](https://github.com/wuba/react-native-echarts/assets/30792140/6eff9f53-55c3-4320-ac86-c11ce6e8f149)

```
export default function App() {
  echarts.use([SVGRenderer, LineChart, GridComponent, VisualMapComponent, MarkAreaComponent, MarkLineComponent]);

  options = {... some chart options}

  const chartRef = useRef<any>(null);

  useEffect(() => {
    let chart: any;
    if (chartRef.current) {
      chart = echarts.init(chartRef.current, 'light', {
        renderer: 'svg',
        width: 380, // if width = CHART_SIZE, cannot show full axis number
        height: CHART_SIZE,
      });
      chart.setOption(option);
    }
    return () => chart?.dispose();
  }, []);

  return (
    <View // wrapper view
      style={{
        height: CHART_SIZE,
        width: CHART_SIZE,
        borderWidth: 1,
      }}
    >
      <SvgChart ref={chartRef} />
    </View>
  );
}

const CHART_SIZE = 320;

```

**Comment by iambool** [comment]
The marked portion of the chart is not a space, but part of the chart. By the way, it is recommended that you use the grid property of echarts to control the layout of the chart's interior. Reference [document](https://echarts.apache.org/zh/option.html#grid.left)
```javascript
const CHART_SIZE = 320;

export default function App() {
  echarts.use([
    SVGRenderer,
    LineChart,
    GridComponent,
    VisualMapComponent,
    MarkAreaComponent,
    MarkLineComponent,
  ]);

  const option = {
    grid: { // use grid
      top: '14%',
      bottom: '14%',
      left: '14%',
      right: '6%',
    },
    backgroundColor: '#effa',
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    yAxis: {
      type: 'value',
    },
    series: [
      {
        data: [150, 230, 224, -218, 135, 147, 260],
        type: 'line',
      },
    ],
  };

  const chartRef = useRef<any>(null);

  useEffect(() => {
    let chart: any;
    if (chartRef.current) {
      chart = echarts.init(chartRef.current, 'light', {
        renderer: 'svg',
        width: CHART_SIZE, // if width = CHART_SIZE, cannot show full axis number
        height: CHART_SIZE,
      });
      chart.setOption(option);
    }
    return () => chart?.dispose();
  }, []);

  return (
    <View // wrapper view
      style={{
        height: CHART_SIZE,
        width: CHART_SIZE,
        borderWidth: 1,
      }}
    >
      <SvgChart ref={chartRef} />
    </View>
  );
}

```

**Comment by NguyenHoangMinhkkkk** [comment]
> 

hi, thanks.

the grid setting works. but with long series number like 10.000 or some number longer still mess the layout

**Comment by iambool** [comment]
do you mean like this?
<img width="327" alt="截屏2023-09-12 17 57 24" src="https://github.com/wuba/react-native-echarts/assets/30134533/6fc9b723-ab65-4171-8fc0-4cadfba610d8">

**Comment by iambool** [comment]
grid.containLabel will avoid labels from overflowing the container. Reference [document](https://echarts.apache.org/en/option.html#grid.containLabel)

**Comment by NguyenHoangMinhkkkk** [comment]
> grid.containLabel will avoid labels from overflowing the container. Reference [document](https://echarts.apache.org/en/option.html#grid.containLabel)

yes! thank you. that's exactly what i finding
