### ISSUE TITLE
visualMap and ZoomDataComponent wrong working together ?

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [wuba/react-native-echarts#119]
Demo working fine: [DEMO](https://echarts.apache.org/examples/en/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoW7YCIDmAnCAJpgFzJoYWZigmwBMALADTkXqYBGwY1AtrQwAcLNhkwAbAKYAzMLWGs2mfNgAWc0gGY6I0VgDGMMAEMI0ADLGOk8bTC4ArpMUBfXewAeAQQ8QAzrSoelhcDtAExrgAngDixiB2jpLuSn4g4hBg5maSgYrBmH6qwADutNLG4n7OwW75YmBRILmkmPrGYJLYwNGYKZQRJrQA2vWimAAME8RTfWNKEwCMMxNzwZQTdCtr6-wTmtv9epMMh_MbAKxnu3sAbNc3kwDsD7uTgq_rkwCcnwWL01mR3Gi2WQPOYkWW3BNywiwOMMei1OiLeiyuqK-i3umP-L1xx0WHwJIN-JKUdEBq2BFLB1Ih7Do0PpsMwdARq3mAF0aZhjL4_NloC0yKyiqVypVqjTKH4orwuOIAPLSaTVDSwUawigTGV6CYM2Bc-Z1Ar8_wAFQg-gA1nkxcUyqQKlUanpTcdzYKrDZ7Y9eJFsGZaFC9expEYAMoQABeIoBJtcKUwUR8_j940azVomAAbpUnDtxmkMlkchmvuKnbAXdUTbzeGYAJLQTq4fO2UiLXleoUioKPKuS11hrByhXAZWq9UjQ060c6w3G2o9gVW20VgpD51St2iD3jAMeHPslnHRvQWi6-Z8gWWayd0X-wPBru3RMUA9jyT4SQBUhanoA5vFmIoSOWo6FLwwDcKoiROJB46Kjm0AwLkkEZMKkaNFIm6PCUhBgHBpB0IaX4FIMxiztqGAMN8AB0FwXAutEMU8twcZxnEsegFwTPRDB0Mxc4YBciz0U8Qk8bAFyaPRdDfNiXEcdJTH0ZoTzCTRvFPBJFyCJohlGZoqkMRcUkiegtz8d80l0KC9ETAwSnKXZDmCIpykqZZsC3OJ3wWdpvl0PRtzGeF0nQA44jiJF0WxT5UUxXFyWJfFKUJUFSWZdp2UZflaUxUukEBrgNp9nhbx-BAUitvByQ-eBWE4f2PmUIY4g9DmHDiIW0mUARBBESG_UNE0YF-JOhCYD55GPOIPqPsBQVjo6w51kFc1VfKyEAW1YiocKRYrZgh25D5PKNZR1Eregy23ewqYCiGmmMft6AuBdZElZENpeLgkhUaQ92PNde0PZq71sCDEOPWm_6wIsr1abD4yZJIvDYVEuHA1DrIdV1uOozRbSTj02GgAjgHE9pMM09qmDANOkgate9MPaTnW4DmuDYBwxgABRCcxAI6ACzATAAlDN7M0VtsuiHTCsFEzaosyNePE5zhNYLz_NC0xTCi0bTlMPxtzS5rt2fcreiXbb4zHqQbMO5QURXqNt2YB4dAe1bDNRL7XaeydoE5phgPcyHQU4J1_OPrWe7Kzbssp6j8tBUrHNPemJFCRJzleVxTz-2nK3LtpFe7GXn6KPbYi5v4DiVAAsvEN2K4amAgBAkj6H-HfalnbwXi9FyMSHmBHrQmhiZPBPc60UQ2J1ZSzcVXfbjWu6QcADhgCqABKxjQNgrUxwv3W9edsI1xgZf1-wlEAFowfw4NAV3YetGY1UEOhXcLyRhACfDWrILwADUCySGAaArs9Z5jDywN_McGR_5Ry7qoSQEA1AakpJBLgPBgDv0RrcDCMgNTaEgiodQM8dCALMLAy8wcGHQCgdfJhIYPwYGNC4AA3EAA)

I copy exact the demo's option object into example code in RN. and problem come like the video below. 
i don't really know the problem come from echart issues or my wrong implementing ?
-------------
    "@wuba/react-native-echarts": "^1.2.3",
    "echarts": "^5.4.3",
    "react-native": "0.72.3"
-------------
https://github.com/wuba/react-native-echarts/assets/30792140/2325fc2b-5d9a-41d2-b789-28843c717105

**Comment by yechunxi** [comment]
The reason for this rendering exception is the presence of many null values in the data. you can start by handling these null values in the data by setting them to default values. We will find a better solution to avoid this issue.

**Comment by NguyenHoangMinhkkkk** [comment]
> The cause of the problem is that the data contains a lot of null values. You can first handle these null values as default values. We will find a better solution to avoid this issue.

Thanks for replying!

My data collection is unpredictable, so the array probably contains null/NaN/undefined/int/floats... 
then i try to convert these variable into 2 accepted type => [number | null]. 

For now, the chart working good with visualMap already, only facing problem with zoomData which is the "nice to have" feature. i will try to make more data senarios

Thank you!
