### ISSUE TITLE
Problem with markLine not being displayed

### ISSUE THREAD

**Issue by wunai-max** [wuba/react-native-echarts#125]
**Describe the bug**
The markLine property cannot display the set dotted line

**To Reproduce**
 const option = {
      xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      },
      yAxis: {
        type: 'value',
      },
      series: [
        {
          data: [150, 230, 224, 218, 135, 147, 260],
          type: 'line',
          markLine: {
            silent: false,
            data: [
              {
                name: '平均线',
                type: 'average',
                xAxis: new Date().getTime(),
              },
              {
                name: 'Y 轴值为 100 的水平线',
                yAxis: 110,
              },
            ],
          },
        },
      ],
    };
  this.chart = echarts.init(this.skiaRef, 'light', {
        renderer: 'svg',
        width: winWidth,
        height: height ?? 320,
      });
 this.chart.setOption(option);
render() {
  return (<SvgChart ref={ele => (this.skiaRef = ele)} />)
} 

**Expected behavior**
The markLine attribute can take effect

**Screenshots**
![image](https://github.com/wuba/react-native-echarts/assets/70249773/a51c1cf3-163c-4a6f-a322-71ca57685b71)

**Desktop (please complete the following information):**
Version
echarts  5.4.3
@wuba/react-native-echarts 1.2.4
@shopify/react-native-skia  0.1.210  
react-native  0.71.3
react 18.2.0

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: ios16.4

**Additional context**

**Comment by wunai-max** [comment]
import {SVGRenderer, SvgChart} from '@wuba/react-native-echarts';
import {LineChart} from 'echarts/charts';
import {GridComponent, TooltipComponent} from 'echarts/components';
import * as echarts from 'echarts/core';
echarts.use([SVGRenderer, LineChart, GridComponent, TooltipComponent]);

**Comment by yechunxi** [comment]
I can't reproduced your problem. Can you provide a demo of the reproduction?   The information you provided is rendered using svg. You can also provide the `react-native-svg` version.

**Comment by wunai-max** [comment]
> 我无法重现你的问题。能提供一下复现的demo吗？您提供的信息是使用 svg 呈现的。您也可以提供`react-native-svg`版本。

Using skia or svg markLine attribute can not take effect, the appeal code is the demo I used in the project, the version of react-native svg is 9.13.6, and the version of @shopify/react-native skia is 0.1.210

**Comment by wunai-max** [comment]
[TestEchart.txt](https://github.com/wuba/react-native-echarts/files/12890360/TestEchart.txt)
demo 
![25A81131-B9CE-43EB-9E02-45BB2A5FA938](https://github.com/wuba/react-native-echarts/assets/70249773/378af9ec-b2ec-4142-a43e-b0ac2466fe6f)

**Comment by yechunxi** [comment]
@wunai-max  The reason for this problem is that you do not use echarts `MarkLineComponent` in your project. Modify the following code to display it normally.

```js
import {GridComponent, TooltipComponent,  MarkLineComponent} from 'echarts/components';
echarts.use([SVGRenderer, LineChart, GridComponent,TooltipComponent, MarkLineComponent]);

```
