### ISSUE TITLE
Unexpected token 'export': ´export * from './lib/module/svgChart'´ when using Next.js & Expo in monorepo

### ISSUE THREAD

**Issue by daniel-heg** [wuba/react-native-echarts#127]
Hi, 
first of all, thank you for this lib! 

I am using the expo & next.js starter from tamagui ([source here](https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito)). 
And I ran into the following issue when using the `SvgChart` while running on "web" (Expo / React Native does work):

```
export * from './lib/module/svgChart';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

I am importing like this (so there is no problem with Skia): 
```
import SvgChart, { SVGRenderer } from '@wuba/react-native-echarts/svgChart'
```

Also, I have tried to add the Webpack extensions to `next.conf.js` like explained [here](https://wuba.github.io/react-native-echarts/docs/advanced-guides/use-in-react#custom-react-projects), but that did not work,

I also tried adding `@wuba/react-native-echarts/svgChart` to the `transpilePackages` Array, but that did not work either.

What am I doing wrong?

Thank you

**Comment by zhiqingchen** [comment]
https://github.com/wuba/react-native-echarts/issues/95

**Comment by daniel-heg** [comment]
Yes, I found that issue and tried everything from that thread. 

But I am on '1.2.5' and it somehow does not work.

**Comment by zhiqingchen** [comment]
Can you provide a complete demo repository

**Comment by daniel-heg** [comment]
Thank you, but that won't be necessary. I finally found the solution!

In `next.js` I had to put the whole package name into the `transpilePackages` array, not just the `.../svgChart`. 
So if anyone else has the same Problem, my `next.config.js` looks like this to make the package work:

```
...
    transpilePackages: [
      ...,
      'echarts',
      'zrender',
      '@wuba/react-native-echarts'
    ],
...
```

**Comment by zhiqingchen** [comment]
Thanks for providing this information!
