### ISSUE TITLE
animation not work

### ISSUE THREAD

**Issue by krmao** [wuba/react-native-echarts#128]
**Describe the bug**
set option about any animation is not work

**To Reproduce**

```
        animation: true,
        animationDuration: 7000,
        animationEasing: 'linear',
        animationThreshold: 0,
        animationDelay: 1000,
        animationDurationUpdate: 1000,
        animationEasingUpdate: 1000,
        animationDelayUpdate: 1000,
```

**Expected behavior**
show a initial animation or update animation

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: both
 - Version 1.2.5

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone15 PRO max]
 - OS: [e.g. iOS 17.0]

**Additional context**
none

**Comment by yechunxi** [comment]
I can't reproduced your problem. Can you provide a demo of the reproduction?

**Comment by krmao** [comment]
@yechunxi  sorry, it's not a bug, because **animationThreshold: 0,** auto disable the animation, I will close the issue.
