### ISSUE TITLE
TypeError: Cannot read property 'trigger' of null, js engine: hermes

### ISSUE THREAD

**Issue by rameesp** [wuba/react-native-echarts#137]
TypeError: Cannot read property 'trigger' of null, js engine: hermes 

![Screenshot 2023-11-09 at 17 54 26](https://github.com/wuba/react-native-echarts/assets/35191339/5fc5dea3-a836-4daa-8e86-ddf3344e86af)

I am unable to find the root cause of this issue, it's happening frequently while hot reloading the app
OS :  Android 13

**Comment by zhiqingchen** [comment]
https://github.com/wuba/react-native-echarts/issues/92

**Comment by nguyenthetuan** [comment]
i also the same problem as you

**Comment by rameesp** [comment]
> i also the same problem as you

https://github.com/wuba/react-native-echarts/issues/92#issuecomment-1742007174

**Comment by renishdeveloper** [comment]
Experiencing the same in my react native app, when the application hot reloads the issue is getting in some cases, not every time.
May be the trigger is not getting correctly.

**Comment by zhiqingchen** [comment]
zrender 5.5.0
echarts 5.5.0-rc.1

The new version fixes this problem, you can try it.
