### ISSUE TITLE
Sync prop changes

### ISSUE THREAD

**Issue by alexey-yarmosh** [wuba/react-native-echarts#141]
I am using an example component from the https://wuba.github.io/react-native-echarts/docs/getting-started/write-a-dynamic-data-chart with the difference that my data is coming from props. Upper component updates values every second.

The bug is that after the emulator opens, I can see that chart rerenders fully every second, which is reasonable. But in ~5 seconds I see an error:
<img width="403" alt="image" src="https://github.com/wuba/react-native-echarts/assets/16905445/b1c4ffe2-52a3-4b73-890e-a3f9ffbea760">

As I understand, chart is not supposed to be rerendered on every props change. Instead rerender should be canceled and something like `chart.setOption()` called in the meantime. If that is true can you please provide an example? I guess that is a general usage for many users to get the data from the upper state and sync it over time.

**Comment by alexey-yarmosh** [comment]
Ok, after some searching on other github repos solution seems to be:
```jsx
    const [chartInstance, setChartInstance] = useState(null);

    // Initialization
    useEffect(() => {
        if (chartRef.current && !chartInstance) {
            const chart = echarts.init(chartRef.current, 'light', {
                renderer: 'svg',
                width: E_WIDTH,
                height: E_HEIGHT,
            });
            setChartInstance(chart); // Store the chart instance in the state
        }
    }, []);

    // Data Update
    useEffect(() => {
        if (chartInstance) {
            chartInstance.setOption(option);
        }
    }, [data]);
```
Hope that is correct implementation. Original link: https://github.com/windalfin/fasttt/blob/ff30b40a040700e5fc99f807fa96cda3951ca01d/src/components/HomePage/FastingProgressGauge.tsx#L86-L105

**Comment by yechunxi** [comment]
> Ok, after some searching on other github repos solution seems to be:
> 
> ```js
> const [chartInstance, setChartInstance] = useState<EChartsType | null>(null);
>   const skiaRef = useRef(null);
> 
>   useEffect(() => {
>     let chart: EChartsType | null = null;
>     if (skiaRef.current && !chartInstance) {
>       chart = echarts.init(skiaRef.current, 'light', {
>         renderer: 'svg',
>         width: E_WIDTH,
>         height: E_HEIGHT,
>       });
>       chart.setOption(options);
>       setChartInstance(chart);
>       return () => chart?.dispose();
>     }
>   }, []);
> 
>   useEffect(() => {
>     chartInstance?.setOption(options);
>   }, [data]);
> ```
> 
> Hope that is correct implementation. Original link: https://github.com/windalfin/fasttt/blob/ff30b40a040700e5fc99f807fa96cda3951ca01d/src/components/HomePage/FastingProgressGauge.tsx#L86-L105


@alexey-yarmosh  Did this approach solve your problem?  This is the correct implementation. When options change, instead of re-creating the echart instance, directly call setOption to re-render the chart.

However, some users still find that page switching is too fast and errors occasionally occur. After the echart instance is destroyed, some internal operations may continue to cause errors.  like  this [discussion](https://github.com/wuba/react-native-echarts/issues/92).  We also submitted a PR to zrender to solve the change problem, but the PR is still waiting for official verification and merging.

**Comment by yechunxi** [comment]
> Yes, seems to be working for now. If some issues arise I'll get back here. Also probably that usage worth documenting on the website, I can assist with that if needed.

Thank you for your suggestion. We will provide the most suitable implementation case for the document. This issue will be closed. If you have other questions, welcome to open a new issue.
