### ISSUE TITLE
The shadowColor on emphasis.itemStyle does not work for bar chart

### ISSUE THREAD

**Issue by lchenfox** [wuba/react-native-echarts#142]
**Describe the bug**

`shadowColor` does not work for bar chart.

**To Reproduce**

The `option` configs

```
const option = {
	useCoarsePointer: false,
	tooltip: {
		trigger: "axis",
	},
	xAxis: [
		{
			type: "category",
			data: ["2023-09-09", "2023-09-10", "2023-09-11", "2023-09-12", "2023-09-13", "2023-09-14", "2023-09-15"],
		},
	],
	yAxis: [{type: "value"}],
	series: [
		{
			name: "Direct",
			type: "bar",
			emphasis: {
				disabled: false,
				itemStyle: {
					color: 'green',
					borderWidth: 1,
					shadowBlur: 10,
					shadowColor: 'red',
				}
			},
			data: ["--", "--", "--", "912", "--", "--", "--"],
		},
	],
};
```

**Expected behavior**

The `emphasis.itemStyle` works as expected in `option` when the user clicks the bar chart. It should look like
![1821704434087_ pic_hd](https://github.com/wuba/react-native-echarts/assets/22851821/2f1c31a8-5b4b-49e6-ac0a-8b5a9fc57c7c)

**Screenshots**

However, it looks like this

![1831704434088_ pic_hd](https://github.com/wuba/react-native-echarts/assets/22851821/e9fe0399-d9e0-44f7-ae0b-677969de3251)

**Desktop (please complete the following information):**

```
info Fetching system and libraries information...
System:
  OS: macOS 12.5
  CPU: (8) arm64 Apple M2
  Memory: 106.39 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.4.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.7.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/chenlong/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Package.json**

```
  "dependencies": {
    "@wuba/react-native-echarts": "^1.2.5", 
    "echarts": "^5.4.3", 
    "react": "18.2.0",
    "react-native": "0.72.0", 
    "react-native-svg": "^13.7.0", 
    "react-native-webview": "^11.26.0", 
  },
```

**Comment by zhiqingchen** [comment]
https://github.com/software-mansion/react-native-svg/issues/150
shadow is not yet supported in react native svg.

**Comment by lchenfox** [comment]
> [software-mansion/react-native-svg#150](https://github.com/software-mansion/react-native-svg/issues/150) shadow is not yet supported in react native svg.

Thank you for your reply. I tried to use `SkiaChart` but it still does not work. So, is `shadow` not yet supported in either type of chart?

**Comment by zhiqingchen** [comment]
yes
https://shopify.github.io/react-native-skia/docs/images-svg#non-supported-elements

**Comment by lchenfox** [comment]
I get it, thanks a lot. Hope it can be solved soon. Closing this issue because I see there is already a known issue open: [issue16](https://github.com/wuba/react-native-echarts/issues/16).
