### ISSUE TITLE
skiaChart legend custom fontFamily not work but  other rn normal component works

### ISSUE THREAD

**Issue by krmao** [wuba/react-native-echarts#148]
- setOption not work about legend fontFamily, it is a custom load font
> assets: ['./src/assets/fonts/D-DIN-Bold.ttf'] in react-native.config.js
```
legend: {
        textStyle: {
          fontFamily: 'D-DIN-Bold',
```

- other works example code in style, both yet works on android and ios
```
  xxxStyle: {
    fontFamily: 'D-DIN-Bold',
  },
```

- version
```
"@shopify/react-native-skia": "^0.1.213"
"@wuba/react-native-echarts": "^1.2.3"
"echarts": "^5.4.3"
```

**Comment by Jakub-Plan-d-k** [comment]
@krmao I am pretty sure this is an issue with Skia itself. I have reported that here:
https://github.com/Shopify/react-native-skia/issues/1894

**Comment by krmao** [comment]
@Jakub-Plan-d-k Thank you for your dedicated response, which has helped me understand the key information. Fortunately, this issue did not block my work. I will close this issue and keep watching. Thanks again!
