### ISSUE TITLE
New architecture support 

### ISSUE THREAD

**Issue by maneesh-techversant** [wuba/react-native-echarts#149]
**Is your feature request related to a problem? Please describe.**
I just wanted to know if echarts supports react native new architecture, if not when can I expect Echarts to migrate to fabric

**Describe the solution you'd like**
Echart supporting the new architecture

**Comment by zhiqingchen** [comment]
React-native-echarts contains only js code, and whether it supports the new architecture depends on which rendering library you're using and whether its version supports it.

Check out the related projects:
https://github.com/Shopify/react-native-skia
https://github.com/software-mansion/react-native-svg
