### ISSUE TITLE
Please merge feat/react-native-73 to be able to use Expo 50 which is not working

### ISSUE THREAD

**Issue by abpbackup** [wuba/react-native-echarts#151]

**Comment by zhiqingchen** [comment]
What are the detailed errors?
feat/react-native-73 will be merged after development is complete.

**Comment by zhiqingchen** [comment]
you can try new version
[1.3.0-alpha.0](https://www.npmjs.com/package/@wuba/react-native-echarts/v/1.3.0-alpha.0)

**Comment by mfrfinbox** [comment]
Hey @zhiqingchen thanks, for me the issue was not being able to use it with Expo Go, I realised I needed to use a development build, thanks. It was working
