### ISSUE TITLE
Add Support for Comparison Series in Line/Area Charts

### ISSUE THREAD

**Issue by zaidqureshi95** [wuba/react-native-echarts#159]
**Feature Request**

I'm currently utilizing echarts for visualizing data in my React Native application. While the library offers robust features for plotting individual series on line and area charts, I've encountered a scenario where comparing multiple data series side-by-side within the same chart would significantly enhance data analysis and user experience.

Plot multiple data series on the same chart canvas, allowing for direct comparison of trends and patterns.
Customize the appearance (color, thickness, etc.) of each series for clear distinction.
Incorporate interactive elements such as tooltips that dynamically update to display information relevant to the series under focus, enhancing data exploration for users.

**Comment by zhiqingchen** [comment]
Please provide an example of its use

**Comment by zaidqureshi95** [comment]
Uploading Screen Recording 2024-02-29 at 4.03.41 PM.mov…

**Comment by zhiqingchen** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=data-transform-filter

**Comment by zaidqureshi95** [comment]
its for web but I need a component where I can give my own data to populate

**Comment by zhiqingchen** [comment]
same.
https://github.com/wuba/taro-playground/blob/main/src/pages/explore/charts/pages/line/lineStack.tsx

**Comment by zaidqureshi95** [comment]
> same. https://github.com/wuba/taro-playground/blob/main/src/pages/explore/charts/pages/line/lineStack.tsx

doesn't it have simple component to use stack line rather to using custom View and style components?

**Comment by zhiqingchen** [comment]
see apache Echarts documents
