### ISSUE TITLE
Chart becomes very slow when rendering large volume of data

### ISSUE THREAD

**Issue by GokuVijay** [wuba/react-native-echarts#166]
**Describe the bug**
Importing a large amount of data into ECharts significantly slows down the application, it even unresponsive to any events. I'm using React Native SVG for chart rendering.

**Expected behavior**
The chart becomes significantly slow specifically when loading a large volume of data. How to overcome this issue ?

**Screenshots**
<img width="742" alt="image" src="https://github.com/wuba/react-native-echarts/assets/84261226/5d185482-60be-497b-b1fb-c0489b824725">

**Smartphone (please complete the following information):**
 - IOS simulator iphone 12 mini

**Comment by lucaswitch** [comment]
There is too much views on your rendering tree.

**Comment by GokuVijay** [comment]
Is there any possible way to **render large volume of data** ? 

We have planned to use this package for our application despite the presence of this issue; however, everything else works perfectly fine.

**Comment by lucaswitch** [comment]
**Page the chart data** or **make a approximation** to use lowest number of data possible.
**Any chart library can become slow** as the data grows too big.
Think the charts as something like Google Maps, you can't plot the whole city so as we zoom through the map new details should appear, as we zoom out the datails fade away but we can see the whole.

**Comment by GokuVijay** [comment]
Thanks for the insight!
