### ISSUE TITLE
[Question] Is this RN 74 / Expo 51 ready?

### ISSUE THREAD

**Issue by sem4phor** [wuba/react-native-echarts#175]
Hello,

I was wondering if anybody made this package run on RN 74 / Expo 51?
We are currently upgrading and on web the chart is invisible (whereas the tooltip is visible) and on native the chart is not rendering at all (we are using it within a webview there with react-native-webview + react-native-react-bridge)

**Comment by zhiqingchen** [comment]
https://github.com/wuba/react-native-echarts/tree/main/example

The demo is now using expo51, you can try it first
