### ISSUE TITLE
 ReferenceError: Property 'document' doesn't exist

### ISSUE THREAD

**Issue by ceu** [wuba/react-native-echarts#176]
"@shopify/react-native-skia": "^1.2.3",
    "@wuba/react-native-echarts": "^1.3.1",
 "react-native-svg": "^15.3.0",

**Comment by ceu** [comment]
why  react-native use document?

**Comment by ceu** [comment]
@58code

**Comment by ceu** [comment]
![WechatIMG219](https://github.com/wuba/react-native-echarts/assets/13114273/09b64893-8ab5-45e7-bd56-f3d1a9499a3d)

**Comment by gufengpiaoyi** [comment]
咋解决的

**Comment by zachTrio** [comment]
What was the solution?
