### ISSUE TITLE
Not working with expo-router

### ISSUE THREAD

**Issue by zachTrio** [wuba/react-native-echarts#185]
**Describe the bug**
Graphs will not render when using expo-router.
When space is interacted with, throws error:
`Cannot read property 'handler' of undefined.` from `dispatchEventsToZRender`

**To Reproduce**
1. Get the example project within this repo
2. Follow steps to manually add expo-router [here](https://docs.expo.dev/router/installation/#manual-installation)
3. Delete `App.js`
4. Rename `src/App.tsx` to `src/app/index.tsx`
5. Run the project. Screen will be blank.
6. Tapping on where the graphs would be will throw error.

**Expected behavior**
Graph should behave as intended.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**
 - Device: Galaxy A54 5G
 - OS: Android 14

**Comment by zhiqingchen** [comment]
I tried the reprolapse step, and it worked normally.

**Comment by hareruya-maro** [comment]
I was experiencing the same error, but after upgrading echarts to version ^5.5.1, the error stopped occurring.

**Comment by zhiqingchen** [comment]
There may be multiple zrender or echarts libraries in your project. Can you check them?
```
yarn why zrender
```

**Comment by zhiqingchen** [comment]
Can you provide an example that can be reproduced

**Comment by DmitryEremenko** [comment]
> Can you provide an example that can be reproduced

Just run latest expo application and add basic example from your library.
Web - all charts on place
mobile - no charts rendered

Everything latest Expo 51, echarts and react-native-echarts, expo-router used as routing solution
