### ISSUE TITLE
使用Pie图，渲染动画结束后消失

### ISSUE THREAD

**Issue by arafat813** [wuba/react-native-echarts#212]
使用的官方实例，改了一下数据
`
data: [
      { value: 100, name: 'Search Engine' },
      { value: 0, name: 'Direct' },
      { value: 0, name: 'Email' },
      { value: 0, name: 'Union Ads' },
      { value: 0, name: 'Video Ads' }
    ]
`
发现如果只有一个数值大于0，其他都等于会出现消失的情况，两个就不会，应该如何修复

https://github.com/user-attachments/assets/2ccad8a0-3d30-46cb-a65d-f0cca6d65abf

**Comment by arafat813** [comment]
目前发现，可以将等于0的数值等于0.01，就能实现图不会消失

**Comment by zhiqingchen** [comment]
2.0.1

**Comment by arafat813** [comment]
2.0.1可以用
