### ISSUE TITLE
Unrecognized font family 'sans-serif'

### ISSUE THREAD

**Issue by sa1utep1z** [wuba/react-native-echarts#216]
I keep encountering errors while using this component library, but they can be closed. However, they keep reappearing after being closed. The packaged app works fine, but in the development environment, this error keeps popping up, affecting my development workflow. How can I avoid this issue?

Thank you for taking the time to look into this issue. I look forward to your response.🫡🫡

This is my system and libraries information:
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M3
    Memory: 100.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
    Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    Android SDK:
      API Levels: 30, 31, 33, 34
      Build Tools: 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
      Android NDK: 26.1.10909125
  IDEs:
    Android Studio: 2023.2 AI-232.10300.40.2321.11567975
    Xcode: 15.3/15E204a - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

This is a video showing the issue.

https://github.com/user-attachments/assets/38b29f59-5b05-4aab-a9f3-1258469e8317

![IMG_8CF4B604AB93-1](https://github.com/user-attachments/assets/a4beaab5-efb1-430a-b23c-8f790a374ffa)

**Comment by zhiqingchen** [comment]
https://github.com/wuba/react-native-echarts/commit/e40f28fc4b0c12e1850da651cde2a86d78e7c527

Problems that may be related

**Comment by zhiqingchen** [comment]
try 2.0.2

**Comment by sa1utep1z** [comment]
> try 2.0.2

可以了，谢谢🙏！
