### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSkiaModule' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by qy-jscoder** [wuba/react-native-echarts#224]
**Describe the bug**
你好，我是react native的初学者，在使用该插件时遇到了问题，还请指教。我使用SvgChart时能正常使用，但是在使用SkiaChart时产生报错 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSkiaModule' could not be found. Verify that a module by this name is registered in the native binary. 最初我以为是版本太高导致的报错，便将@shopify/react-native-skia降低版本到1.5.0，但是仍然报错

**To Reproduce**
1、封装了图表组件
import { useRef, useEffect } from 'react';
import * as echarts from 'echarts/core';
import { BarChart, LineChart, PieChart } from 'echarts/charts';
import {
    DataZoomComponent,
    GridComponent,
    LegendComponent,
    TitleComponent,
    ToolboxComponent,
    TooltipComponent,
} from 'echarts/components';
import {
    SVGRenderer,
    SkiaRenderer,
    SvgChart as _SvgChart,
    SkiaChart as _SkiaChart,
} from '@wuba/react-native-echarts';
import { Dimensions } from 'react-native';

// 注册需要用到的组件
echarts.use([
    DataZoomComponent,
    SVGRenderer,
    BarChart,
    GridComponent,
    LegendComponent,
    ToolboxComponent,
    TooltipComponent,
    TitleComponent,
    PieChart,
    LineChart,
    SkiaRenderer
]);

// 图表默认宽高
const CHART_WIDTH = Dimensions.get('screen').width; // 默认用手机屏幕宽度
const CHART_HEIGHT = 300;

const Chart = ({
    option,
    onInit,
    width = CHART_WIDTH,
    height = CHART_HEIGHT,
    ChartComponent,
}) => {
    const chartRef = useRef(null);

    useEffect(() => {
        let chart;
        if (chartRef.current) {
            chart = echarts.init(chartRef.current, 'light', {
                renderer: 'svg',
                width: width - 68,
                height,
            });
            option && chart.setOption(option);
            onInit?.(chart);
        }
        return () => chart?.dispose();
    }, [option]);
    return <ChartComponent ref={chartRef} />;
};

const SkiaChart = (props) => <Chart {...props} ChartComponent={_SkiaChart} />;
const SvgChart = (props) => <Chart {...props} ChartComponent={_SvgChart} />;
export { SkiaChart, SvgChart };

2、在使用时引入
import { SkiaChart } from '../echarts'
...
const option={xxx}
<SkiaChart option={option}  />

3、报错
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSkiaModule' could not be found. Verify that a module by this name is registered in the native binary.

**Screenshots**
![image](https://github.com/user-attachments/assets/ed06f3bb-0d93-4a5a-bea8-8f8bbd9ae6ab)

版本信息：
"react": "18.2.0",
"react-native": "0.71.3",
"react-native-svg": "15.2.0",
"@shopify/react-native-skia": "1.5.0",
"@wuba/react-native-echarts": "^2.0.2",
"echarts": "^5.6.0"

**Comment by zhiqingchen** [comment]
提供个完整的可复现仓库吧

**Comment by qy-jscoder** [comment]
> 提供个完整的可复现仓库吧

感谢你的回答，我这里已经解决了，在删除node包重新安装后可以使用

**Comment by qy-jscoder** [comment]
> 提供个完整的可复现仓库吧

感谢你的回答，我将之前尝试的其他echarts插件删除并重新安装node包后可以正常使用
