### ISSUE TITLE
pieChart  不支持graphic， legend  这些吗

### ISSUE THREAD

**Issue by nanahenniu** [wuba/react-native-echarts#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iambool** [comment]
这些都是支持的，使用时需要注册对应的组件，比如：
```javascript
echarts.use([
  SVGRenderer,
  GridComponent,
  PieChart, LegendComponent, GraphicComponent // 引入使用到的组件
]);
```
