### ISSUE TITLE
SvgChart不支持markPoint？

### ISSUE THREAD

**Issue by moonlight1002** [wuba/react-native-echarts#48]
## SvgChart option 增加 markPoint 不显示

const option = {
  animation: true,
  tooltip: {
    show: false,
  },
  grid: {
    top: "20%",
    left: 17,
    right: 17,
    bottom: "20%",
  },
  xAxis: [
    {
      type: "time",
      axisLabel: {
        fontSize: 10,
        align: "center",
        showMaxLabel: true,
        formatter: "{MM}.{dd}",
      },
      axisPointer: {
        type: "shadow",
      },
      axisLine: {
        show: true,
        lineStyle: {
          color: "#CCD2E3",
          align: "left",
          cap: "round",
        },
      },
      splitLine: {
        show: true,
        interval: 0,
        lineStyle: {
          type: "dashed",
        },
      },
      axisTick: {
        show: false,
      },
    },
  ],
  yAxis: [
    {
      show: false,
      type: "value",
      min: 0,
      max: 100,
      interval: 20,
      axisTick: {
        lineStyle: {
          color: "rgba(104, 183, 219, 0.2)",
        },
      },
      axisLabel: {
        formatter: "{value}",
        fontSize: 10,
        color: "#333",
      },
    },
  ],
  series: [
    {
      name: "效率",
      type: "line",
      symbol: "circle",
      connectNulls: true,
      symbolSize: 6,
      itemStyle: {
        color: "#77C176",
      },
      labelLine: {
        lineStyle: {
          color: "#f00",
        },
      },
      lineStyle: {
        width: 1,
        color: "#77C176",
      },
      label: {
        show: true,
        position: "top",
        distance: 8,
        formatter: "{@[1]}%",
        fontSize: 10,
        color: "#77C176",
        fontWeight: "400",
        lineHeight: 11,
      },
      markPoint: {
        emphasis: {
          disabled: true,
        },
        animation: false,
        data: [
          {
            name: "markPoint",
            value: "",
            xAxis: "2022-04-24",
            yAxis: 0,
            symbol: "circle",
            symbolSize: [10, 10],
            itemStyle: { color: "#FFC700" },
          },
        ],
      },
      data: [
        ["2022-04-18", 10],
        ["2022-04-19", 20],
        ["2022-04-20", "unchecked"],
        ["2022-04-21", "x"],
        ["2022-04-22", 100],
        ["2022-04-23", "checkable"],
        ["2022-04-24", "today"],
      ],
    },
  ],
};

"@wuba/react-native-echarts": "^1.0.0"
 "echarts": "^5.4.2",

**Comment by moonlight1002** [comment]
xAxis axisLabel.fontSize 也不生效
![image](https://user-images.githubusercontent.com/47058891/231623307-426ed9de-fe97-47c9-8ff3-12fd8e9e7ac5.png)

**Comment by iambool** [comment]
Svg模式中，**markPoint是支持的**，参见下方截图；但是Svg中，**xAxis.axisLabel.fontSize** 的设置确实没有生效，这一点我们会改下，感谢反馈。以上两个点，Skia模式都是支持的，在问题未修复前，可考虑先使用Skia绘图
<img width="278" alt="1681353946831" src="https://user-images.githubusercontent.com/30134533/231634834-367b4f42-714c-4305-bfd7-fd98978caa16.png">
<img width="227" alt="1681353989282" src="https://user-images.githubusercontent.com/30134533/231634935-6a242611-3a69-4360-99cd-25dc36bfbd9a.png">

**Comment by moonlight1002** [comment]
> Svg模式中，**markPoint是支持的**，参看下方截图；但是是Svg中，**xAxis.axisLabel.fontSize**的设置确实没有产生效果，这一点我们会改下，谢谢反贴。在问题未修复前，可考虑先使用Skia绘图 <img alt="1681353946831" width="278" src="https://user-images.githubusercontent.com/30134533/231634834-367b4f42-714c-4305-bfd7-fd98978caa16.png"> <img alt="1681353989282" width="227" src="https://user-images.githubusercontent.com/30134533/231634935-6a242611-3a69-4360-99cd-25dc36bfbd9a.png">



> svg模式，**markpoint是支持支持**，svg中s，svg**中**中使用Skia绘图 <img alt="1681353946831" width="278" src="https://user-images.githubusercontent.com/30134533/231634834-367b4f42-714c-4305-bfd7-fd98978caa16.png"> <img alt="1681353989282" width="227" src="https://user-images.githubusercontent.com/30134533/231634935-6a242611-3a69-4360-99cd-25dc36bfbd9a.png">

我这边模拟器，真机都无法显示markPoint，是什么版本啊

**Comment by moonlight1002** [comment]
我这边模拟器，真机都无法显示markPoint，是什么版本啊 @iambool

**Comment by iambool** [comment]
> 我这边模拟器，真机都无法显示markPoint，是什么版本啊 @iambool

我使用了你上方贴的版本，机型是iphone8、华为Nova5Pro. 你使用的是什么机型呢，尽可能提供多点参数，我尝试复现看看

**Comment by iambool** [comment]
我的配置：
"@wuba/react-native-echarts": "1.0.0",
"echarts": "5.4.2",
"react-native-svg": "13.7.0",
"@shopify/react-native-skia": "^0.1.156",

**Comment by moonlight1002** [comment]
> > 我这边模拟器，真机都无法显示markPoint，是什么版本啊@iambool
> 
> 我用了你上面贴的版本，机型是iphone8、华为Nova5Pro。你用的是什么机型呢，尽管可能提供多点参数，我试试复现看

![image](https://user-images.githubusercontent.com/47058891/231680758-d3cd053e-fc5d-44e0-b680-b1138fbe7b67.png)
真机是华为mate 30 pro

 "react-native-svg": "^13.3.0",

**Comment by moonlight1002** [comment]
`import React, { useEffect, useRef } from 'react';
import { StyleSheet, Dimensions, View } from 'react-native';
import SvgChart, { SVGRenderer } from '@wuba/react-native-echarts/svgChart';
import * as echarts from 'echarts/core';
import { LineChart } from 'echarts/charts';
import { TitleComponent, TooltipComponent, GridComponent } from 'echarts/components';
import { options } from './config';

// register extensions
echarts.use([TitleComponent, TooltipComponent, GridComponent, SVGRenderer, LineChart]);

const { width } = Dimensions.get('screen');

function SvgComponent(props: { option: any }) {
  const { option = {} } = props || {};
  const svgRef = useRef<any>(null);

  useEffect(() => {
    let chart: any;
    if (svgRef.current) {
      chart = echarts.init(svgRef.current, 'light', {
        renderer: 'svg',
        width: width - 68,
        height: 180
      });
      chart.setOption(option);

      chart.on('click', function (params: any) {
        console.log('click params: ', params);
      });
    }
    return () => chart?.dispose();
  }, [option]);

  return <SvgChart ref={svgRef} />;
}

const SvgChartDemo: React.FC = props => {
  return (
    <View style={styles.container}>
      <SvgComponent option={options} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' }
});

export default SvgChartDemo;
`

**Comment by zhiqingchen** [comment]
你使用的react-native-svg版本是多少？
```
yarn why react-native-svg
```

**Comment by moonlight1002** [comment]
> 

react-native-svg@13.9.0

**Comment by moonlight1002** [comment]
> 你使用的react-native-svg版本是多少？
> 
> ```
> yarn why react-native-svg
> ```

react-native-svg@13.9.0

**Comment by iambool** [comment]
我用低版本的svg（13.3.0）可以复现上方的问题，所以，尝试高版本的svg看看

**Comment by moonlight1002** [comment]
> > > 你使用的react-native-svg版本是多少？
> > > ```
> > > yarn why react-native-svg
> > > ```
> > 
> > 
> > react-native-svg@13.9.0
> 
> 这个版本也出不来markpoint吗

没有显示

**Comment by moonlight1002** [comment]
react-native-svg@13.9.0 react-native-svg@13.7.0 都试过了，都不显示markpoint

**Comment by iambool** [comment]
svg版本升级后，有没有重新编译原生APP呢；如果没有，重新打App包看看

**Comment by moonlight1002** [comment]
> svg版本升级后，有没有重新编译原生APP呢；如果没有，重新打App包看看
编译了，没显示， 跟rn版本有关系？
react-native@0.69.7
yarn
cd ios
pod install
xcode 重新运行安装到模拟器

android用真机重新安装的

**Comment by moonlight1002** [comment]
![image](https://user-images.githubusercontent.com/47058891/231721410-9ece7aa4-f63b-46c2-9f3b-111f863e8673.png)

**Comment by iambool** [comment]
我这边目前是 "react-native": "^0.70.5"
我试试看0.69

**Comment by iambool** [comment]
> > svg版本升级后，有没有重新编译原生APP呢；如果没有，重新打App包看看
> 
> 编译了，没显示， 跟rn版本有关系？ react-native@0.69.7 yarn cd ios pod install xcode 重新运行安装到模拟器 android用真机重新安装的

我尝试了0.69.7，svg用的13.7.0，markpoint也是能出来的；你那边有进展吗

**Comment by moonlight1002** [comment]
> > > svg版本升级后，有没有重新编译原生APP呢；如果没有，重新打App包看看
> > 
> > 
> > 编译了，没显示， 跟rn版本有关系？ react-native@0.69.7 yarn cd ios pod install xcode 重新运行安装到模拟器 android用真机重新安装的
> 
> 我尝试了0.69.7，svg用的13.7.0，markpoint也是能出来的；你那边有进展吗
不显示，还没来得及看。。

**Comment by yangfeihu** [comment]
"react-native": "^0.71.6",
"react-native-svg": "^13.9.0",
"@shopify/react-native-skia": "^0.1.197",
"@wuba/react-native-echarts": "^1.2.1",

我这边的markPoint也显示不了，能不能把这个问题修复下

**Comment by yangfeihu** [comment]
问题已经解决，需要导入  MarkPointComponent 组件：
import { MarkPointComponent } from 'echarts/components';
