### ISSUE TITLE
Error: Unable to resolve module @shopify/react-native-skia from 

### ISSUE THREAD

**Issue by shmjiao** [wuba/react-native-echarts#53]
react-native-echarts V1.0.0
node: 18.15.0
react: 18.1.0
expo: ~47.0.9
导入方式：
`import SvgChart, {SVGRenderer} from '@wuba/react-native-echarts/svgChart';
import {SVGRenderer, SkiaChart} from '@wuba/react-native-echarts';`

问题原因：刚开始发现svg形式在web上不能用，android可以，就在web开发上用了SkiaChart，skiaChart可以在web上成功运行，但在android报错Error: Unable to resolve module @shopify/react-native-skia from 

根据https://shopify.github.io/react-native-skia/docs/getting-started/web执行了如下命令
`expo install @shopify/react-native-skia`

现在运行起来后报错，执行不了
`Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4 from D:\workspaces\xfa\one-app/.: 
None of these files exist:
  * debugger-ui\debuggerWorker.aca173c4(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json)`

请问是什么原因导致的问题？

**Comment by zhiqingchen** [comment]
导入方式1：
```
import SvgChart, {SVGRenderer} from '@wuba/react-native-echarts/svgChart';
```
或
导入方式2：
```
import SkiaChart, {SVGRenderer} from '@wuba/react-native-echarts/skiaChart';
```

**Comment by shmjiao** [comment]
react-native:0.70.8

**Comment by shmjiao** [comment]
> 导入方式1：
> 
> ```
> import SvgChart, {SVGRenderer} from '@wuba/react-native-echarts/svgChart';
> ```
> 
> 或 导入方式2：
> 
> ```
> import SkiaChart, {SVGRenderer} from '@wuba/react-native-echarts/skiaChart';
> ```

还是会报那个错，并且这样引入skiaChart后，web端也加载失败，会报这三个错误
`SVGRenderer.web.js:5 Uncaught Error: Module parse failed: Unexpected token (22:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // }
|   const initString = svg ? Skia.SVG.MakeFromString(svg) : undefined;
>   return initString ?? undefined;
| }
| function SkiaComponent(props, ref) {
    at ./node_modules/@wuba/react-native-echarts/lib/module/skiaChart.js 

index.js:1 ./node_modules/@wuba/react-native-echarts/lib/module/skiaChart.js 22:21
Module parse failed: Unexpected token (22:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // }
|   const initString = svg ? Skia.SVG.MakeFromString(svg) : undefined;
>   return initString ?? undefined;
| }
| function SkiaComponent(props, ref) {


Uncaught ReferenceError: process is not defined
`

**Comment by zhiqingchen** [comment]
web 目前支持在expo web 中运行

1. clone 该项目，进入 example 目录
2. 运行 `yarn start`
3. 输入 `w` 打开浏览器

其他自行搭建的环境没有验证过，需提供可复现demo。

或参考 [react native web 的配置](https://necolas.github.io/react-native-web/docs/multi-platform/)。

核心配置：
```
{
  resolve: {
    // This will only alias the exact import "react-native"
    alias: {
      'react-native$': 'react-native-web'
    },
    // If you're working on a multi-platform React Native app, web-specific
    // module implementations should be written in files using the extension
    // `.web.js`.
    extensions: [ '.web.js', '.js' ]
  }
}
```
