### ISSUE TITLE
点击图表没有反应

### ISSUE THREAD

**Issue by ShichuanZhang** [wuba/react-native-echarts#56]
我使用的是1.1.1版本, 在安卓端环境.
生成图表后, 点击图表和图例都没有任何反应. 没有弹出数据标签, 也不会根据图例隐藏数据, 图例也不会变色.

**Comment by zhiqingchen** [comment]
1. 是否使用了 RNGH
2. 尝试用 expo 运行 demo

https://wuba.github.io/react-native-echarts/docs/expo-snacks/large-area-chart-use-rngh
