### ISSUE TITLE
Android设备饼图中文乱码

### ISSUE THREAD

**Issue by kaziii** [wuba/react-native-echarts#57]
option
```js
{
      color: chartColors,
      grid: {
        left: "5%",
        right: "5%",
        top: "10%",
        bottom: 100,
        height: "80%",
        containLabel: true,
      },
      legend: {
        itemHeight: 16,
        itemWidth: 16,
        data: legend,
        itemGap: 16,
        right: 20,
        orient: "horizontal",
        y: "bottom",
        x: "center",
        top: 180,
        selectedMode: false,
        textStyle: {
          color: "#999",
        },
        formatter: function (name) {
          // 不进行换行 返回20字符的名称
          return name.length > 20 ? name.substr(0, 20) + "..." : name;
        },
      },
      series: [
        {
          name: "详情",
          type: "pie",
          center: ["50%", "90"],
          radius: [40, 60],
          avoidLabelOverlap: false,
          silent: true,
          labelLine: {
            normal: {
              show: true,
              length: 10,
              length2: 80,
            },
          },
          label: {
            show: true,
            borderWidth: 20,
            borderRadius: 4,
            padding: [0, -80],
            textStyle: {
              color: "#999",
            },
            formatter: (params) => {
              return `${
                params.data.value > 10000
                  ? `${(params.data.value / 10000).toFixed(2)}万`
                  : params.data.value
              }${unit} ${params.percent}%\n`;
            },
          },
          emphasis: {
            label: {
              show: true,
              fontSize: "12",
              fontWeight: "bold",
            },
          },
          labelLayout: {
            color: "red",
          },
          data: series,
          clickable: false,
        },
      ],
    };
```
配置
```js
import React, { useRef, useEffect } from "react";
import * as echarts from "echarts/core";
import { PieChart } from "echarts/charts";
import { GridComponent, LegendComponent } from "echarts/components";
import SkiaChart, { SVGRenderer } from "@wuba/react-native-echarts/skiaChart";
import { Dimensions } from "react-native";

echarts.use([SVGRenderer, PieChart, GridComponent, LegendComponent]);
const E_HEIGHT = 210;
const E_WIDTH = Dimensions.get("screen").width;
export default function BaseAndroidOrIosCharts({ option }) {
  const skiaRef = useRef(null);
  useEffect(() => {
    let chart;
    if (skiaRef.current) {
      chart = echarts.init(skiaRef.current, "light", {
        renderer: "svg",
        width: E_WIDTH,
        height: E_HEIGHT,
      });
      if (option) {
        chart.setOption(option);
      }
    }
    return () => chart?.dispose();
  }, [option]);

  return <SkiaChart ref={skiaRef} />;
}
```
![1683256314172](https://user-images.githubusercontent.com/12526958/236370562-d960f061-ea55-4b10-93b1-1ef67c5a1353.jpg)

**Comment by zhiqingchen** [comment]
尝试
1. 使用svgchart
2. 给label等设置系统支持的字体

**Comment by kaziii** [comment]
使用svgchart 显示正常，但是过渡动画卡顿
设备 小米10s

**Comment by zhiqingchen** [comment]
性能上，skia更好点，通过设置字体也可以解决中文问题

**Comment by zhangyongz** [comment]
> 性能上，skia更好点，通过设置字体也可以解决中文问题
设置过字体以后，tooltip里面中文还是不显示

**Comment by zhangyongz** [comment]
设置了字体，legend的中文显示了，tooltip里还是不显示

**Comment by zhiqingchen** [comment]
@zhangyongz 提供下具体配置和环境信息

**Comment by zhangyongz** [comment]
`option = {
    backgroundColor: '#fff',
    legend: {
      show: true,
      icon: 'roundRect'
    },
    tooltip: {
      trigger: 'axis',
      backgroundColor: 'rgba(0,0,0,0.65)',
      textStyle: {
        color: '#fff',
        fontSize: 12,
        textStyle: {
          fontFamily: 'PingFang SC'
        }
      },
      axisPointer: {
        type: 'line',
        lineStyle: {
          color: '#E6262C4D',
          type: 'dashed'
        },
        width: 2
      }
    },
    xAxis: {
      type: 'category',
      data: [
        '05-02',
        '05-03',
        '05-04',
        '05-05',
        '05-06',
        '05-07',
        '05-08'
      ]
    },
    yAxis: [
      {
        show: true
      },
      false
    ],
    series: [
      {
        show: true,
        animation: true,
        type: 'line',
        name: '收件量',
        data: [
          1022.92,
          997.24,
          925.7,
          991.55,
          1040.35,
          514.87,
          49
        ]
      },
      {
        show: true,
        animation: true,
        type: 'line',
        name: '均量',
        data: [
          791.66,
          791.66,
          791.66,
          791.66,
          791.66,
          791.66,
          791.66
        ]
      }
    ],
    textStyle: {
      fontFamily: 'PingFang SC'
    }
  }`

`
dependencies: {
  react-native: "0.70.6",
  echarts: "5.4.2",
  @wuba/react-native-echarts: "1.0.0",
  @shopify/react-native-skia: "0.1.188"
}
`

**Comment by iambool** [comment]
> `option = { backgroundColor: '#fff', legend: { show: true, icon: 'roundRect' }, tooltip: { trigger: 'axis', backgroundColor: 'rgba(0,0,0,0.65)', textStyle: { color: '#fff', fontSize: 12, fontFamily: 'PingFang SC' }, axisPointer: { type: 'line', lineStyle: { color: '#E6262C4D', type: 'dashed' }, width: 2 } }, xAxis: { type: 'category', data: [ '05-02', '05-03', '05-04', '05-05', '05-06', '05-07', '05-08' ] }, yAxis: [ { show: true }, false ], series: [ { show: true, animation: true, type: 'line', name: '收件量', data: [ 1022.92, 997.24, 925.7, 991.55, 1040.35, 514.87, 49 ] }, { show: true, animation: true, type: 'line', name: '均量', data: [ 791.66, 791.66, 791.66, 791.66, 791.66, 791.66, 791.66 ] } ], textStyle: { fontFamily: 'PingFang SC' } }`
> 
> `dependencies: { react-native: "0.70.6", echarts: "5.4.2", @wuba/react-native-echarts: "1.0.0", @shopify/react-native-skia: "0.1.188" }` @zhiqingchen

也是小米10吗，还是别的机型？

**Comment by zhangyongz** [comment]
ios @iambool

**Comment by Error4O4-NotFound** [comment]
> 设置了字体，legend的中文显示了，tooltip里还是不显示 @zhiqingchen

![image](https://github.com/wuba/react-native-echarts/assets/12546065/e857bc5b-611d-4c4a-a2ba-ab61dc3832b9)
使用了SkiaCharts，tooltip中不显示中文的可以将这个文件的这几段注释打开，DEFAULT_FONT_FAMILY改为PingFang SC
一个临时的解决方法

**Comment by zjjjjjjjjjjd** [comment]
楼主最后怎么解决的

**Comment by shellyaoo** [comment]
> 性能上，skia更好点，通过设置字体也可以解决中文问题

我用的就是skia但是中文还是乱码，不管设置什么字体

**Comment by zhiqingchen** [comment]
@shellyaoo  换 2.0 试试
