### ISSUE TITLE
Multiple Instances of the same chart

### ISSUE THREAD

**Issue by robinvk6** [wuba/react-native-echarts#59]
I have a question regarding displaying multiple instances of the Line Chart with different datasets. Is there an example on how I can accomplish that. I tried passing different ref objects to SVGChart but it always takes the data properties of the second chart.

**Comment by zhiqingchen** [comment]
> I tried passing different ref objects to SVGChart but it always takes the data properties of the second chart.

Can you describe how you use it, or provide the code.

**Comment by robinvk6** [comment]
Sorry this was a mistake on my side.
