### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by mateoguzmana** [wuba/react-native-echarts#6]
Any plans to support web in this library?

I was running the example in a project where I have set up `react-native-skia` with `expo` & `react-native-web` and I got this error when running it for web. iOS/Android work fine. Using the example code in the README.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/20783123/215278277-d265fa3c-27b9-4e10-9a5b-6c42c5688786.png">

**Comment by zhiqingchen** [comment]
web is no support yet, we will try it.

**Comment by zhiqingchen** [comment]
web is now supportted @0.1.6

https://wuba.github.io/react-native-echarts/docs/expo-snacks/simple-line-chart
