### ISSUE TITLE
Infinite re-render with callback ref

### ISSUE THREAD

**Issue by MrSquaare** [wuba/react-native-echarts#61]
**Describe the bug**
Passing a callback ref to SkiaChart or SvgChart cause component to be infinite re-rendered.
This might be due to missing deps array for `useImperativeHandle`

**To Reproduce**
1. Pass a callback ref to SkiaChart or SvgChart
2. React error

**Expected behavior**
Re-render only if necessary

**Comment by zhiqingchen** [comment]
Hi @MrSquaare, can you provide the code or demo, I used the `ref` callback function and didn't find the error.

**Comment by zhiqingchen** [comment]
[1.1.2-alpha.0](https://www.npmjs.com/package/@wuba/react-native-echarts/v/1.1.2-alpha.0)
