### ISSUE TITLE
Custom(ize) gestures

### ISSUE THREAD

**Issue by MrSquaare** [wuba/react-native-echarts#64]
**Is your feature request related to a problem? Please describe.**
Today, it is impossible to customize the behavior of defined gestures.

**Describe the solution you'd like**

For `react-native-gesture-handler`:
- Listen to gesture events
- Modify the properties of defined gestures (Example: wait for a long pressure before activating the Pan gesture, so as not to block scrolling in a `ScrollView`)
- Add new gestures that are listened to in race of defined gestures
- Overload defined gestures (which requires the user to forward events to zrender correctly, kind of tricky)

For custom gesture logic:
- Apart from listening events, it will be difficult to achieve the other points

Common:
- Being able to disable gestures (a simpler solution instead of overloading defined gestures, user will also be responsible for event forwarding)

**Describe alternatives you've considered**
- Allow user to use the `react-native-gesture-handler` API onto existing gestures

**Comment by zhiqingchen** [comment]
Very interesting idea, the implementation should be complicated, maybe you can try provide a pr.
