### ISSUE TITLE
也许react-native-gesture-handler是一个更好的选择？

### ISSUE THREAD

**Issue by chj-damon** [wuba/react-native-echarts#7]
相比于React Native自带的PanResponder，RNGH在处理手势问题上优势更加明显，我看现在代码里还是用的PanResponder，是不是可以考虑替换成RNGH呢？

**Comment by zhiqingchen** [comment]
目前使用 PanResponder，并未看到太大问题，已知的问题是 scrollview 滚动与图表操作的冲突。

当然我们也会尝试一下 RNGH，有大的优势会考虑替换，如果没有太大优势，可以减少一个库的安装，适用范围更广。

**Comment by pavelbabenko** [comment]
@zhiqingchen I'd be very nice if you move to react-native-gesture-handler or make it an option

**Comment by zhiqingchen** [comment]
### Answered by GPT-4
Thank you for your suggestion; we greatly appreciate feedback from developers. We will seriously consider your recommendation to replace React Native's built-in PanResponder with react-native-gesture-handler (RNGH). Allow me to first explain the advantages of these two libraries.

PanResponder is a gesture handling library built into React Native. It can handle various gesture actions and is tightly integrated with the React Native framework. However, PanResponder's functionality is relatively limited, and it may not be sufficient for some complex gesture operations.

On the other hand, react-native-gesture-handler is an independent gesture handling library with richer features and better performance. Its advantages include:

0. More accurate gesture recognition and handling: RNGH can more accurately recognize and handle various gestures, improving the interactivity of applications.
1. Better performance: RNGH outperforms PanResponder, especially when dealing with a large number of gesture operations.
2. Better cross-platform compatibility: RNGH supports more platforms, including iOS and Android.
3. More flexible API: RNGH provides a richer API, allowing developers to customize gesture handling logic.

Given these advantages, we will seriously consider replacing PanResponder with react-native-gesture-handler. We will evaluate our existing code to determine the cost of replacement and potential issues. Additionally, we will consider offering react-native-gesture-handler as an option, allowing developers to choose the gesture handling library according to their needs.

Please give us some time to assess this suggestion. In the meantime, if you have any recommendations or ideas regarding the implementation process, feel free to comment on this issue. We will respond and make a decision as soon as possible. Thank you again for your suggestion!

### Me

Very good advice, I will try to get GPT to assist in writing the code

**Comment by krmao** [comment]
@zhiqingchen ***已知的问题是 scrollview 滚动与图表操作的冲突*** 这个问题有解决方案吗？useRNGH={true} 开启后 SkiaChart in ScrollView 不能滑动
