### ISSUE TITLE
Android cannot respond to click events

### ISSUE THREAD

**Issue by yinyanli** [wuba/react-native-echarts#74]
Android cannot respond to click events

**Comment by zhiqingchen** [comment]
More information is needed
1. demo or code
2. the corresponding version number, react-native, react-native-skia/react-native-svg, @wuba/react-native-echarts

**Comment by yinyanli** [comment]
react-native: 0.62.2

**Comment by yinyanli** [comment]
没有收到showTip事件

**Comment by iambool** [comment]
尝试复现，目前安卓和ios都能触发showtip，请问这个效果不符合预期吗？
![show](https://github.com/wuba/react-native-echarts/assets/30134533/8e95125e-3d63-46df-8d5e-77771b2f4438)

**Comment by yinyanli** [comment]
@iambool 你的看起来符合预期的，但是在我的设备上，安卓点击没反应，ios正常，能分享下你的demo吗

**Comment by iambool** [comment]
我复现时的环境：
华为鸿蒙OS2.0
react-native 0.71.6
react-native-svg 13.9.0

其余依赖跟你在上方贴的一致
