### ISSUE TITLE
Responsive Charts

### ISSUE THREAD

**Issue by tjapa** [wuba/react-native-echarts#76]
How can I make the charts responsive in height and width?

**Comment by zhiqingchen** [comment]
The width and height of the chart needs to be set during initialization. If you want to change the container width and height dynamically, you can do so with the resize method.

```
myChart.resize({
  width: 800,
  height: 400
});
```

https://echarts.apache.org/handbook/en/concepts/chart-size/

**Comment by tjapa** [comment]
Thank you!
