### ISSUE TITLE
In Pie Chart : SvgChart doesn't renders scrollable legend properly in Android

### ISSUE THREAD

**Issue by DarshanKSPL** [wuba/react-native-echarts#87]
I am using import SvgChart, {SVGRenderer} from '@wuba/react-native-echarts/svgChart'; to display a bar chart in the mobile application.

I have used a bar chart in my mobile application. but when I use a Bar chart using the type:'scroll' attribute with limited 8 items it is working fine, each bar chart functionality is working fine. But when I add 10 more items to the bar chart and then scroll arrows are displayed on the screen but the list is displayed for a fraction of a second and then disappears from the screen and then if I press the next or previous arrow keys to view the next list items is shows list items for the fraction of seconds and again disappears.

**Expected behavior**
The pie chart should display the list of items on the screen, list items should not disappear from the screen.

**Screenshots**

**Limited data size:**
![Screenshot_1688982443](https://github.com/wuba/react-native-echarts/assets/103264769/88901ac8-d610-437b-8bae-82d22bbfeeff)

**Data size of more than 15**

https://github.com/wuba/react-native-echarts/assets/103264769/c4e7f853-d0bc-48a8-9742-6af6120d868f

**Comment by zhiqingchen** [comment]
same issue #82

**Comment by zhiqingchen** [comment]
The issue is still being fixed, and a temporary solution is available:
1. use skia instead
2. use alpha version 1.2.2-alpha.3

**Comment by DarshanKSPL** [comment]
@zhiqingchen  It is working fine with Skia. @zhiqingchen  Thank you for helping me out.

**Comment by zhiqingchen** [comment]
You're welcome @DarshanKSPL
