### ISSUE TITLE
[Solved] Not displayed at all

### ISSUE THREAD

**Issue by issaysa** [wuba/react-native-echarts#88]
**Describe the bug**
Nothing will be rendered if zrender version is not same as the echarts' zrender version.
I think it is better to write about zrender version in "Getting Started".

**To Reproduce**
1. Create fresh react-native project.
2. Do exactly as "Getting Started→Installation"
3. Do exactly as "Write a simple line chart"
4. No any graph will be displayed.

**Expected behavior**
Graph should be rendered.

**Desktop (please complete the following information):**
 - OS: Mac M1 Ventura 13.4

**How to Solve the problem**
in package.json
if echarts version is 5.4.1, you need to add zrender 5.4.1
if echarts version is 5.4.2, you need to add zrender 5.4.3

**Comment by zhiqingchen** [comment]
Thanks for pointing it out.

**Comment by zhiqingchen** [comment]
hi @issaysa , can you submit the demo to Github?

**Comment by issaysa** [comment]
@zhiqingchen 
Hi, I found out that I used npm not yarn, and that was the problem.
When I use yarn, it works fine. (Sorry I didn't follow the installation process exactly as it says.)
Npm somehow installs zrender 5.4.4 at the same time. Here's the minimal reproduction.
[https://github.com/issaysa/react-native-echarts-npm-issue](https://github.com/issaysa/react-native-echarts-npm-issue)

**Comment by zhiqingchen** [comment]
It's true that there is a problem with multiple versions of zrender when using npm. It is recommended to use yarn.

```sh
➜  react-native-echarts-npm-issue git:(main) npm explain zrender
zrender@5.4.3
node_modules/echarts/node_modules/zrender
  zrender@"5.4.3" from echarts@5.4.2
  node_modules/echarts
    echarts@"^5.4.1" from the root project
    peer echarts@"*" from @wuba/react-native-echarts@1.2.1
    node_modules/@wuba/react-native-echarts
      @wuba/react-native-echarts@"^1.2.1" from the root project

zrender@5.4.4 peer
node_modules/zrender
  peer zrender@"*" from @wuba/react-native-echarts@1.2.1
  node_modules/@wuba/react-native-echarts
    @wuba/react-native-echarts@"^1.2.1" from the root project
```

**Comment by zhiqingchen** [comment]
try `yarn-deduplicate`
Cleans up yarn.lock by removing duplicates.

**Comment by zhiqingchen** [comment]
Alternatively, upgrading echarts to 5.4.3 will also fix this issue
