### ISSUE TITLE
是否支持自适应高度

### ISSUE THREAD

**Issue by 18605161612** [wuba/react-native-echarts#91]

**Comment by zhiqingchen** [comment]
还未得到支持

**Comment by zhiqingchen** [comment]
初始化取节点高度

通常来说，需要在 HTML 中先定义一个 <div> 节点，并且通过 CSS 使得该节点具有宽度和高度。初始化的时候，传入该节点，图表的大小默认即为该节点的大小，除非声明了 opts.width 或 opts.height 将其覆盖。

主动监听屏幕变化，调整高度

监听图表容器的大小并改变图表大小
在有些场景下，我们希望当容器大小改变时，图表的大小也相应地改变。

比如，图表容器是一个高度为 400px、宽度为页面 100% 的节点，你希望在浏览器宽度改变的时候，始终保持图表宽度是页面的 100%。

这种情况下，可以监听页面的 resize 事件获取浏览器大小改变的事件，然后调用 [echartsInstance.resize](https://echarts.apache.org/api.html#echartsInstance.resize) 改变图表的大小。

https://echarts.apache.org/handbook/zh/concepts/chart-size

@xuanweiH

**Comment by zhiqingchen** [comment]
https://wuba.github.io/react-native-echarts/docs/expo-snacks/adaptive-size-chart
