### ISSUE TITLE
Unable to resolve "@shopify/react-native-skia"

### ISSUE THREAD

**Issue by tjapa** [wuba/react-native-echarts#95]
Im getting this error when a try to run the app with Expo in Android. I'm using the react-native-svg.

```
Android Bundling failed 5672ms
Unable to resolve "@shopify/react-native-skia" from "../../packages/app/node_modules/@wuba/react-native-echarts/src/skiaChart.tsx"
```

**Comment by zhiqingchen** [comment]
https://wuba.github.io/react-native-echarts/docs/advanced-guides/import-individually

**Comment by tjapa** [comment]
When I changed:
```import { SvgChart, SVGRenderer } from '@wuba/react-native-echarts'```

Per:
``` import SvgChart, { SVGRenderer } from '@wuba/react-native-echarts/svgChart'```

I get the following error in Next.JS: 
![image](https://github.com/wuba/react-native-echarts/assets/17579637/c48a3520-67ed-4a6e-99e0-28bd98c50018)

```TypeError: root.appendChild is not a function```

**Comment by zhiqingchen** [comment]
so you want to use in Android and next ?

**Comment by zhiqingchen** [comment]
If you want to use it in next.js, you need to add some configuration like this:

https://wuba.github.io/react-native-echarts/docs/advanced-guides/use-in-react#custom-react-projects

**Comment by zhiqingchen** [comment]
Can you verify this on version `1.2.2-alpha.4`?

![image](https://github.com/wuba/react-native-echarts/assets/1876158/fcabb45d-15f7-496b-872f-efc5777f6491)

**Comment by tjapa** [comment]
It looks like it worked on both (NextJS and Expo). Thank you very much! @zhiqingchen
