### ISSUE TITLE
Exporting the graph to an image without rendering to the screen

### ISSUE THREAD

**Issue by gabrielfast** [wuba/react-native-echarts#96]
I'm trying to generate an image of a graph without displaying it on the screen.

In this example in react that it is possible to do this generation by echar:
https://github.com/FrankChen021/node-charts/blob/master/service.js

Would you like to do something similar using Skia.Surface.MakeOffscreen?
https://github.com/Shopify/react-native-skia/discussions/1359

Would you have another suggestion on how to do this generation?

Thks

**Comment by zhiqingchen** [comment]
Images can be generated on the server side

**Comment by WangShayne** [comment]
@zhiqingchen how to export png(base64)? 
```
echarts.getDataURL("png");
```
get undefined

**Comment by zhiqingchen** [comment]
Not supported yet

**Comment by gabrielfast** [comment]
Hey guys,

Worked using react-native-view-shot! 

I used this example as a reference: https://github.com/gre/react-native-view-shot/blob/master/example/Example/src/Offscreen.js

```
<ViewShot ref={viewShotRef} style={{ width, height, position: 'absolute', right: -width - 5 }}>
      <SvgChart ref={chartRef} useRNGH />
</ViewShot>
```

**Important: Does not work with skia, only with SVG**

**Comment by zhiqingchen** [comment]
> Does not work with skia
Do you know why?

**Comment by WangShayne** [comment]
> Hey guys,
> 
> Worked using react-native-view-shot!
> 
> I used this example as a reference: https://github.com/gre/react-native-view-shot/blob/master/example/Example/src/Offscreen.js
> 
> ```
> <ViewShot ref={viewShotRef} style={{ width, height, position: 'absolute', right: -width - 5 }}>
>       <SvgChart ref={chartRef} useRNGH />
> </ViewShot>
> ```
> 
> **Important: Does not work with skia, only with SVG**

Thanks bro,I tried it, both skia and svg can be used

```jsx
import {captureRef} from 'react-native-view-shot';

<View ref={chartViewRef}>
      <SkiaChart ref={chartRef} />
       {/*<SvgChart ref={chartRef} />*/}
</View>

const chartBase64 = await captureRef(chartViewRef, {
       result: 'data-uri',
 });
```

**Comment by gabrielfast** [comment]
> > Hey guys,
> > Worked using react-native-view-shot!
> > I used this example as a reference: https://github.com/gre/react-native-view-shot/blob/master/example/Example/src/Offscreen.js
> > ```
> > <ViewShot ref={viewShotRef} style={{ width, height, position: 'absolute', right: -width - 5 }}>
> >       <SvgChart ref={chartRef} useRNGH />
> > </ViewShot>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Important: Does not work with skia, only with SVG**
> 
> Thanks bro,I tried it, both skia and svg can be used
> 
> ```js
> import {captureRef} from 'react-native-view-shot';
> 
> <View ref={chartViewRef}>
>       <SkiaChart ref={chartRef} />
>        {/*<SvgChart ref={chartRef} />*/}
> </View>
> 
> const chartBase64 = await captureRef(chartViewRef, {
>        result: 'data-uri',
>  });
> ```

Sorry for not being very clear in my answer.

In my use I created a component that receives the data and with a useEffect I update the graph and after rendering I generate the file.

To detect the end of the graph rendering I am using the 'finished' event.

```typescript
  chart.current.on('finished', () => {
    console.log('thumbnail finished');

    viewShotRef.current.capture().then(
      (uri: any) => {
        console.log('thumbnail callback');
      },
      (error: any) => console.error('thumbnail error', error)
    );

    console.log('finished event fired');
  });
}
```

If I'm using skia when the 'finished' event fires the graph doesn't display the data lines.

With SVG it works perfectly when the 'finished' event fires.
